config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :deals
  end
  devise_for :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/categories', to: 'categories#index', as: 'customer'
  get '/', to: 'splash#index'

  # Defines the root path route ("/")
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :customer
  has_and_belongs_to_many :deals
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :deals, dependent: :destroy, foreign_key: 'author_id'
  validates :name, presence: true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'Customer'
  has_and_belongs_to_many :categories
  validates :name, presence: true
  validates :amount, numericality: { only_integer: false, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_customer!

  # GET /categories or /categories.json
  def index
    customer = current_customer
    @categories = customer.categories.all.order(created_at: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.customer = current_customer

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :customer_id)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]
  before_action :authenticate_customer!

  # GET /deals or /deals.json
  def index
    customer = current_customer
    @category = customer.categories.find(params[:category_id])
    @deals = @category.deals.order(created_at: :desc)
  end

  # GET /deals/1 or /deals/1.json
  def show; end

  # GET /deals/new
  def new
    customer = current_customer
    @category = customer.categories.find(params[:category_id])
    @deal = Deal.new
    @other_categories = customer.categories.where.not(id: @category)
  end

  # GET /deals/1/edit
  def edit; end

  # POST /deals or /deals.json
  def create
    customer = current_customer
    @category = customer.categories.find(params[:category_id])
    @deal = Deal.new(deal_params)
    @deal.author = current_customer
    @other_categories = customer.categories.where.not(id: @category)
    categories = Category.where(id: params[:category_ids])
    @deal.categories.push(categories)
    respond_to do |format|
      if @deal.save
        format.html { redirect_to category_deals_url(@category), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { redirect_to category_deals_url(@category), notice: 'Unprocessable transaction.' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1 or /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to deal_url(@deal), notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1 or /deals/1.json
  def destroy
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:author_id, :name, :amount, :category_id, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to categories_path if customer_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/_category.html.erb
<div class="card m-3">
  <div class="d-flex justify-content-between align-items-center mx-2">
    <div>
      <%= image_tag(category.icon, alt: category.name, width: "50") %>
    </div>
    <div>
      <div class="card-body p-0">
        <h5 class="card-title"><%= link_to category.name, category_deals_path(category.id), class: "text-decoration-none align-middle fs-4 regular" %></h5>
      </div>
    </div>
    <div>
      <div class="card-body p-0">
        <p class="card-text fs-5 regular"><%= number_to_currency(category.deals.sum('amount'), unit: '$', precision: 2) %></p>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<% icons = ['american-football', 'astrology', 'baseball', 'basketball', 'billiard', 'bitcoin', 'blueprint',
            'book', 'bowling', 'cabinet', 'camping-tent', 'camping', 'chess', 'circus-tent', 'claim',
            'cleaning', 'cloth', 'coffee', 'coronavirus', 'credit-card- machine', 'cycling', 'dartboard',
            'debit-card', 'degree', 'doctor', 'drink', 'ecology', 'elearning', 'electricity', 'entertainment',
            'espresso', 'family', 'farm', 'fast-food', 'fishing', 'food', 'forklift', 'fruit', 'gadget',
            'gas', 'gift', 'groceries', 'gym', 'ice-cream', 'inbox', 'insurance', 'just-married', 'laundry',
            'loaf', 'magazine', 'massage', 'medical', 'movie', 'music', 'notre-dame', 'painting', 'panorama',
            'parking', 'pets', 'ping-pong', 'pizza', 'poker', 'public-transport', 'puzzle', 'recycle-sign',
            'ring', 'roller-coaster', 'salad', 'salon', 'santa-claus', 'school', 'shopping-cart', 'snack',
            'soap', 'swimming', 'toolbox', 'tooth', 'tow-truck', 'towels', 'toy', 'trail', 'train', 'travel',
            'trekking', 'wedding', 'workspace', 'yoga'] %>  
<%= form_with(model: category) do |form| %>
  <nav class="navbar navbar-expand text-white px-3 mb-3 justify-content-between">
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="navbar-nav">
        <%= link_to '&larr;'.html_safe, categories_path, class: "text-decoration-none text-white fs-2" %>
        <%= form.submit "Save", class:"nav-link bg-transparent border-0 text-decoration-none mx-2" %>
      </div>
    </div>
    <span class="navbar-brand mb-0 fs-4 text-white mx-3">ADD A CATEGORY</span>
  </nav>

  <%= render "partials/message" %>

  <div class="main">
    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.text_field :name, class: "form-control border-0 border-bottom rounded-0 mx-3 px-0 w-100", placeholder: "Category name" %>
      <div class="form-check form-check-inline m-3">
        <% icons.each do |icon| %>
          <%= form.radio_button :icon, "#{icon}.png", id: icon %>
          <%= label_tag icon, image_tag("#{icon}.png", alt: icon, width: "50"), class: "form-check-label m-2" %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/categories/_header.html.erb
<nav class="navbar navbar-expand text-white px-3 justify-content-between">
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
      <%= button_to 'Sign out', destroy_customer_session_path, method: :delete, class: "nav-item nav-link bg-transparent border-0 text-decoration-none" %>
      <%= link_to 'Edit profile', edit_customer_registration_path, class: "nav-item nav-link text-decoration-none" %>
    </div>
  </div>
  <span class="navbar-brand mb-0 fs-4 text-white mx-3">CATEGORIES</span>
</nav>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render "header" %>
<%= render "partials/message" %>

<div class="main">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

<%= link_to "Add a new category", new_category_path, class: "btn add-btn rounded-0 p-3 w-100" %>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/deals/_deal.html.erb
<div class="card m-3">
  <div class="d-flex justify-content-between px-2">
    <div>
      <div class="card-body p-0">
        <p class="card-title text-primary regular fs-4"><%= deal.name %></p>
        <p class="card-text"><small class="text-muted"><%= deal.created_at.strftime('%d %b %Y') %></small></p>
      </div>
    </div>
    <div class="align-self-center">
      <div class="card-body p-0">
        <p class="card-text regular fs-5"><%= number_to_currency(deal.amount, unit: '$', precision: 2) %></p>
      </div>
    </div>
  </div>
</div>

app/views/deals/_form.html.erb
<%= form_with(model: deal, url: category_deals_path(@category)) do |form| %>
  <nav class="navbar navbar-expand text-white px-3 mb-3 justify-content-between">
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="navbar-nav">
        <%= link_to '&larr;'.html_safe, category_deals_path(@category), class: "text-decoration-none text-white fs-2" %>
        <%= form.submit "Save", class:"nav-link bg-transparent border-0 text-decoration-none mx-2" %>
      </div>
    </div>
    <span class="navbar-brand mb-0 fs-4 text-white mx-3">ADD A TRANSACTION</span>
  </nav>

  <%= render "partials/message" %>

  <div class="main">
    <% if deal.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

        <ul>
          <% deal.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.text_field :name, class: "form-control border-0 border-bottom rounded-0 mx-3 px-0 w-100", placeholder: "Transaction name" %>
    </div>

    <div class="form-group">
      <%= form.text_field :amount, class: "form-control border-0 border-bottom rounded-0 mx-3 px-0 w-100", placeholder: "Amount" %>
    </div>
    <div class="form-check form-check-inline m-3">
      <%= form.check_box :category_ids, {multiple: true, checked: true}, @category.id, nil %>
      <label class="form-check-label mr-5 mb-5 active">
        <%= image_tag(@category.icon, alt: @category.name, width: "50") %>
      </label>
      <% @other_categories.each do |category| %>
        <%= form.check_box :category_ids, {multiple: true}, category.id, nil %>
        <label class="form-check-label mr-5 mb-5">
          <%= image_tag(category.icon, alt: category.name, width: "50") %>
        </label>
      <% end %>
    </div>
  </div>
<% end %>

app/views/deals/_header.html.erb
<nav class="navbar navbar-expand text-white px-3 justify-content-between">
  <div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
      <%= link_to '&larr;'.html_safe, categories_path, class: "text-decoration-none text-white fs-2" %>
    </div>
  </div>
  <span class="navbar-brand mb-0 fs-4 text-white mx-3">TRANSACTION - <%= @category.name[..10] %></span>
</nav>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render "form", deal: @deal %>

<br>

<div>
  <%= link_to "Show this deal", @deal %> |
  <%= link_to "Back to deals", deals_path %>
</div>

app/views/deals/index.html.erb
<%= render "header" %>

<%= render "partials/message" %>

<div class="main">
  <p class="m-3 fs-4">Total: <%= number_to_currency(@category.deals.sum('amount'), unit: '$', precision: 2) %></p>

  <% @deals.each do |deal| %>
    <%= render deal %>
  <% end %>

</div>

<%= link_to "Add a new transaction", new_category_deal_path(@category), class: "btn add-btn rounded-0 p-3 w-100" %>

app/views/deals/new.html.erb
<%= render "form", deal: @deal %>

app/views/deals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deal %>

<div>
  <%= link_to "Edit this deal", edit_deal_path(@deal) %> |
  <%= link_to "Back to deals", deals_path %>

  <%= button_to "Destroy this deal", @deal, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Origami</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
      integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous">
    </script>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to customer_signed_in? ? current_customer.name : 'Origami', root_path, class: "text-decoration-none p-3" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if customer_signed_in? %>
          <li class="nav-item p-3">
            <%= button_to 'Sign out', destroy_customer_session_path, method: :delete, class: "nav-link bg-transparent border-0" %>
          </li>
          <li class="nav-item p-3">
            <%= link_to 'Edit profile', edit_customer_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item p-3">
            <%= link_to 'Sign up', new_customer_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item p-3">
            <%= link_to 'Sign in', new_customer_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_message.html.erb
<% flash.each do |type, msg| %>
    <p class="alert  alert-success <%= type %>">
      <%= msg %>
    </p>
<% end %>

app/views/partials/_start.html.erb
<div class="d-flex">
  <div class="card-body min-vh-100">
    <div class="h-50 text-center mt-5">
      <div class="card-image w-100">
        <%= image_tag('house.png', alt: "House of origami", width: "75%") %>
      </div>
    </div>
    <p class="card-title h-25 text-center">Origami</p>
    <div class="h-25 mb-0">
        <%= link_to 'LOG IN', new_customer_session_path,
          class: "btn btn-primary d-flex p-3 mx-3 justify-content-center" %>
        <%= link_to 'SIGN UP', new_customer_registration_path,
          class: "btn btn-outline-secondary border-0 d-flex p-3 mx-3 justify-content-center" %>
    </div>
  </div>
</div>

app/views/splash/index.html.erb
<div class="d-flex">
  <div class="card-body min-vh-100">
    <div class="h-50 text-center mt-5">
      <div class="card-image w-100">
        <%= image_tag('house.png', alt: "House of origami", width: "75%") %>
      </div>
    </div>
    <p class="card-title h-25 text-center">Origami</p>
    <div class="h-25 mb-0">
        <%= link_to 'LOG IN', new_customer_session_path,
          class: "btn btn-primary d-flex p-3 mx-3 justify-content-center" %>
        <%= link_to 'SIGN UP', new_customer_registration_path,
          class: "btn btn-outline-secondary border-0 d-flex p-3 mx-3 justify-content-center" %>
    </div>
  </div>
</div>